# Generated by Django 5.1.8 on 2025-04-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('Art and Literature', 'Arte e letteratura'), ('history', 'Storia'), ('science', 'Scienze'), ('curiosity', 'Curiosità'), ('sport', 'Sport')], max_length=20)),
            ],
        ),
    ]
